#!/usr/bin/python
# -*- coding: utf-8 -*-

# TODO: put a time cache for the data, if not refreshed than it is killed

import sys, os
import re
import pickle
import datetime
import codecs

DEBUG=0
RE_DATA_HEADER=re.compile("data (?P<hostname>\S+)\.unige\.ch.listzone")
FN_LISTZONE='/usr/local/hobbit/server/www/listzone.txt.utf8'
#FN_LISTZONE='/home/briner/git/listzone-solaris-4-xymon/server-side/listzone.txt.utf8'
FN_PICKLE='/usr/local/hobbit/data/data/listzone.pickle'
#FN_PICKLE='/home/briner/git/listzone-solaris-4-xymon/server-side/listzone.pickle'

def getFrenchDate(date=None):
   ''' usage: getFrenchDate(date=today)
              type of date : datetime.date
              if date=None, then date=today
   '''
   import datetime
   if date == None:
      date=datetime.date.today()
   lmonth=[u'janvier', u'février', u'mars', u'avril', u'mai', u'juin', u'juillet', u'août', u'septembre', u'octobre', u'novembre', u'décembre']
   return unicode(date.day)+u' '+lmonth[date.month-1]+u' '+unicode(date.year)

def getFrenchDateTime(mydatetime=None):
   import datetime
   if mydatetime == None:
      mydatetime=datetime.datetime.now()
   ret=u'le %s à %s' % (getFrenchDate(mydatetime.date())
                         ,mydatetime.strftime('%Hh%M'))
   return ret

def getSizeOfList(l):
   return map(lambda x:len(x), l)

def listlist2size(ll, lsize=[]):
   if list != type(ll):
      return 'this listlist is not a list'
   if len(ll)==0:
      return lsize
   if not lsize:
      lsize=getSizeOfList(ll[0])
   for l in ll:
      if list != type(l):
         return 'this list in not constitued of list'
      if len (l) != len (lsize):
         return 'error all the list should be the same lenght'
      ltmpsize=getSizeOfList(l)
      for i in range(len(lsize)):
         if lsize[i] < ltmpsize[i]:
            lsize[i] = ltmpsize[i]
   return lsize

def listlist2nicestr(ll, lsize=[]):
   if not lsize:
      lsize=listlist2size(ll)
   outputFormat=[]
   outputFormatLine=u' '.join( map(lambda x:"%-"+unicode(x)+'s', lsize) )
   output=u''
   for l in ll:
      try:
         output+=outputFormatLine%tuple(l)+u'\n'
      except UnicodeDecodeError, qq:
         print str(type(output)), output
         print l
         print str(type (l[1])),  l[1]
         print str(type (ll[13][1][0])), ll[13][1][0]
         raise qq
   return output

def cmpAlphaNum(str1,str2):
   str1=str1.lower()
   str2=str2.lower()
   ReSplit='(\d+)'
   str1=re.split(ReSplit,str1)
   str2=re.split(ReSplit,str2)
   if( ''==str1[0] ):
      str1.remove('')
   if( ''==str1[len(str1)-1] ):
      str1.remove('')
   if( ''==str2[0] ):
      str2.remove('')
   if( ''==str2[len(str2)-1] ):
      str2.remove('')
   for i in range( min( len(str1),len(str2) ) ):
      try:
         tmp=int(str1[i])
         str1[i]=tmp
      except:ValueError
      try:
         tmp=int(str2[i])
         str2[i]=tmp
      except:ValueError
      if( str1[i]==str2[i] ):
         continue
      if (str1[i]>str2[i]):
         return 1
      else:
         return -1
   return cmp(len(str1),len(str2))

def save_dhost(dhost):
  fd=open(FN_PICKLE, 'w')
  pickle.dump(dhost, fd)
  fd.close()

def load_dhost():
  try:
    fd=open(FN_PICKLE, 'r')
    ret=pickle.load(fd)
    fd.close()
  except:
    ret={}
  return ret

def generate_texte(dhost):
  lkeys=dhost.keys()
  lkeys.sort(cmpAlphaNum)
  lret=[]
  lsize=[]
  for hostname in lkeys:
    lnsize=listlist2size(dhost[hostname]['lzone'],  lsize=lsize)
    lsize=lnsize
  for hostname in lkeys:
    lret.append(hostname+u' '+getFrenchDateTime(dhost[hostname]['datetime']))
    lret=lret+listlist2nicestr(dhost[hostname]['lzone'], lsize=lsize).split('\n')
  return '\n'.join(lret)


dhost=load_dhost()
fd=codecs.open(FN_LISTZONE, 'w', encoding='utf-8')
fd.write(generate_texte(dhost))
fd.close()
del fd

line=sys.stdin.readline()
while line:
  line=line.rstrip()
  line=sys.stdin.readline()
  match=RE_DATA_HEADER.match(line)
  if not match:
    continue
  else:
    sys.stdout.flush()
    hostname=match.groupdict()['hostname']
    line=sys.stdin.readline()
    line.rstrip()
    lzone=[]
    while line:
      line=line.rstrip()
      lzone.append(line.split(':'))
      line=sys.stdin.readline()
      line=line.rstrip()
      if not dhost.get(hostname):
         dhost[hostname]={}
      # regenerate the webpage
      dhost[hostname]['datetime']=datetime.datetime.now()
      dhost[hostname]['lzone']=lzone
      fd=codecs.open(FN_LISTZONE, 'w', encoding='utf-8')
      french_datetime=getFrenchDateTime()
      fd.write (french_datetime+os.linesep)
      fd.write('-'*len(french_datetime)+os.linesep)
      fd.write(generate_texte(dhost))
      fd.close()
      del fd
      # pickle the data
      save_dhost(dhost)
    if DEBUG:
      print 'hostname :', hostname
      print 'datetime :', dhost[hostname]['datetime']
      print 'lzone :', dhost[hostname]['lzone']
      print '-------------------'
      print generate_texte(dhost)
      sys.stdout.flush()
    line=sys.stdin.readline()

#print "je suis dehors"

